language: python
python:
- "3.7"

install:
  - pip install pytest pytest-cov coveralls
  - python setup.py develop
  - pip freeze

before_script:
  - git config --global user.email "edward.oughton@ouce.ox.ac.uk"
  - git config --global user.name "Edward Oughton"

script:
  - python -m pytest --cov=itmlogic tests

after_success:
  - coveralls

notifications:
  email: false

deploy:
  provider: pypi
  user: edwardoughton
  on:
    tags: true
    branch: master
